# Generated by Django 6.0.2 on 2026-04-15 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0003_chatgroup_chat_type_chatgroup_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='join_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='chat_type',
            field=models.CharField(choices=[('public', 'Public'), ('class', 'Class')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
