# Generated by Django 6.0.2 on 2026-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0004_chatgroup_join_code_alter_chatgroup_chat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
