# Generated by Django 6.0.2 on 2026-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0005_groupmessage_attachment_alter_groupmessage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='attachment',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
