# Generated by Django 6.0.2 on 2026-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0006_remove_groupmessage_attachment_groupmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='chat_type',
            field=models.CharField(choices=[('public', 'Public'), ('class', 'Class'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
